#!/bin/bash
rootFile=$1
outDir=`echo $1 | awk -F".root" '{print $1}'`
mkdir -p $outDir
rm -f $outDir/*
root -b -q root2html.C+\(\"$rootFile\"\,\"$outDir\"\)
echo "output in $outDir"
echo "generating html..."

cd $outDir
#HTML=${outDir}.html
HTML="index.html"

PNGFILES=`ls -C1 *png`
cat <<EOF > $HTML
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN"
    "http://www.w3.org/TR/html4/strict.dtd">
<head><title>Systematics directory: $DIRNAME</title></head>
<body>
EOF

for PNG in ${PNGFILES[@]}; do
  echo "<img src=\"$PNG\" title=\"$PNG\" />" >> $HTML
done
cat <<EOF >> $HTML
</body>
</html>
EOF

